site_name: dbt documentation
docs_dir: docs

pages:
- Home: index.md
- Guide:
  - Setup: guide/setup.md
  - Usage: guide/usage.md
  - Building Models: guide/building-models.md
  - Configuring Models: guide/configuring-models.md
  - Database Optimizations: guide/database-optimizations.md
  - Testing: guide/testing.md
  - Best Practices: guide/best-practices.md
  - Package Management: guide/package-management.md
  - Upgrading: guide/upgrading.md
- About:
  - Overview: about/overview.md
  - Viewpoint: about/viewpoint.md
  - License: about/license.md
  - Release Notes: about/release-notes.md
  - Contributing: about/contributing.md

theme: readthedocs
